---
# tasks file for production
- name: Ensure tomcat is present
  apt:
    name: tomcat9
    state: present

- name: Copy war file from assembly  to prod
  synchronize:
    src: "{{ artefact_src }}/{{ artefact }}"
    dest: "{{ artefact_dest }}"
  delegate_to: "{{ artefact_host }}"  
