---
# tasks file for assemb
- name: Ensure maven is present
  apt:
   name: maven
   state: present

- name: Ensure maven is present
  apt:
   name: git
   state: present

- name: Clone a github repository
  git:
   repo: "{{ git_repo }}"
   dest: "{{ home_repos }}"
   clone: yes
   update: yes

- name: "source code : local install"
  command: mvn --batch-mode --quiet install
  args:
    chdir: "{{ home_repos }}"
